#!/bin/sh

# make development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

if [ ! -f "$HOME/.aliases" ]; then
	touch "$HOME/.aliases"
	if [ -f "aliases" ]; then
		cp aliases $HOME/.aliases
	fi
fi

append_to_zshrc 'source $HOME/.aliases'

if [ ! -f "$HOME/.paths" ]; then
	touch "$HOME/.paths"
	if [ -f "paths" ]; then
		cp paths $HOME/.paths
	fi
fi

## storage for python gutils google api creds / keys
if [ ! -d "$HOME/.credentials" ]; then
	mkdir "$HOME/.credentials"
fi

if [ ! -d "$HOME/.keys" ]; then
	mkdir "$HOME/.keys"
fi

append_to_zshrc 'source $HOME/.paths'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

case "$SHELL" in
  */zsh) : ;;
  *)
    fancy_echo "Changing your shell to zsh ..."
      chsh -s "$(which zsh)"
    ;;
esac

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
    rbenv rehash
  fi
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/x11"

# github
brew "git"

# github
brew "hub"

# allows firefox through docker
brew "socat"

# image editing
brew "imagemagick"

#docker
cask "virtualbox"
brew "boot2docker"
cask "dockertoolbox"

#other useful stuff
cask 'google-chrome'
cask 'dropbox'
cask 'github-desktop'
cask 'xquartz'
cask 'atom'
cask 'caffeine'
EOF

if [ ! -f "$HOME/.ssh/github_rsa.pub" ]; then
  fancy_echo "prep github SSH keys"
  open ~/Applications/GitHub\ Desktop.app
fi

echo "192.168.99.100  docker-local.com" | sudo tee -a /etc/hosts
